# Generated by Django 4.1.1 on 2022-09-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
